densenet:
  ratio: 16
  growthRate: 24
  reduction: 0.5
  bottleneck: True
  use_dropout: True

encoder_out: 684
vocab_size: 106
embedding_dim: 256  # 词向量嵌入维度
use_label_mask: False

fusion:
  out_channel: 684
  num_heads: 1
  f_dropout: 0.0

decoder:
  attention_dim: 512
  hidden_dim: 256
  dropout: True
  dropout_p: 0.5

vision_attention_map_path: 'results_sample/vision_map'